var books = [{"book":"EVANGELIUM SECUNDUM MATTHAEUM", "chapters" : [{"chapter":"1", "audio":"matt01.ogg", "verses":[
        {"verse":"1", "start":"6", "end": "11.4", "text":"Liber generationis Iesu Christi filii David filii Abraham."},
        {"verse":"2", "start":"12", "end": "19.8", "text":"Abraham genuit Isaac, Isaac autem genuit Iacob, Iacob autem genuit Iudam et fratres eius,"},
        {"verse":"3", "start":"20", "end": "28.7", "text":"Iudas autem genuit Phares et Zara de Thamar, Phares autem genuit Esrom, Esrom autem genuit Aram,"},
        {"verse":"4", "start":"29", "end": "37", "text":"Aram autem genuit Aminadab, Aminadab autem genuit Naasson, Naasson autem genuit Salmon,"},
        {"verse":"5", "start":"37.2", "end": "46", "text":"Salmon autem genuit Booz de Rahab, Booz autem genuit Obed ex Ruth, Obed autem genuit Iesse,"},
        {"verse":"6", "start":"46", "end": "54", "text":"Iesse autem genuit David regem. David autem genuit Salomonem ex ea, quae fuit Uriae,"},
        {"verse":"7", "start":"54.1", "end": "61", "text":"Salomon autem genuit Roboam, Roboam autem genuit Abiam, Abia autem genuit Asa,"},
        {"verse":"8", "start":"61", "end": "67.5", "text":"Asa autem genuit Iosaphat, Iosaphat autem genuit Ioram, Ioram autem genuit Oziam,"},
        {"verse":"9", "start":"67.5", "end": "74", "text":"Ozias autem genuit Ioatham, Ioatham autem genuit Achaz, Achaz autem genuit Ezechiam,"},
        {"verse":"10", "start":"74", "end": "80.5", "text":"Ezechias autem genuit Manassen, Manasses autem genuit Amon, Amon autem genuit Iosiam,"},
        {"verse":"11", "start":"80.5", "end": "86", "text":"Iosias autem genuit Iechoniam et fratres eius in transmigratione Babylonis."},
        {"verse":"12", "start":"87", "end": "93", "text":"Et post transmigrationem Babylonis Iechonias genuit Salathiel, Salathiel autem genuit Zorobabel,"},
        {"verse":"13", "start":"93", "end": "99.7", "text":"Zorobabel autem genuit Abiud, Abiud autem genuit Eliachim, Eliachim autem genuit Azor,"},
        {"verse":"14", "start":"100", "end": "106.5", "text":"Azor autem genuit Sadoc, Sadoc autem genuit Achim, Achim autem genuit Eliud,"},
        {"verse":"15", "start":"106.5", "end": "113.2", "text":"Eliud autem genuit Eleazar, Eleazar autem genuit Matthan, Matthan autem genuit Iacob,"},
        {"verse":"16", "start":"114", "end": "121.2", "text":"Iacob autem genuit Ioseph virum Mariae, de qua natus est Iesus, qui vocatur Christus."},
        {"verse":"17", "start":"121.8", "end": "140.4", "text":"Omnes ergo generationes ab Abraham usque ad David generationes quattuordecim; et a David usque ad transmigrationem Babylonis generationes quattuordecim; et a transmigratione Babylonis usque ad Christum generationes quattuordecim."},
        {"verse":"18", "start":"141.6", "end": "154", "text":"Iesu Christi autem generatio sic erat. Cum esset desponsata mater eius Maria Ioseph, antequam convenirent inventa est in utero habens de Spiritu Sancto."},
        {"verse":"19", "start":"154.3", "end": "163.3", "text":"Ioseph autem vir eius, cum esset iustus et nollet eam traducere, voluit occulte dimittere eam."},
        {"verse":"20", "start":"164", "end": "180.5", "text":"Haec autem eo cogitante, ecce angelus Domini in somnis apparuit ei dicens: \"Ioseph fili David, noli timere accipere Mariam coniugem tuam. Quod enim in ea natum est, de Spiritu Sancto est;"},
        {"verse":"21", "start":"181", "end": "190", "text":"pariet autem filium, et vocabis nomen eius Iesum: ipse enim salvum faciet populum suum a peccatis eorum\"."},
        {"verse":"22", "start":"191.3", "end": "198.2", "text":"Hoc autem totum factum est, ut adimpleretur id, quod dictum est a Domino per prophetam dicentem:"},
        {"verse":"23", "start":"198.5", "end": "208.2", "text":"\"Ecce, virgo in utero habebit et pariet filium, et vocabunt nomen eius Emmanuel\", quod est interpretatum Nobiscum Deus."},
        {"verse":"24", "start":"209.5", "end": "218", "text":"Exsurgens autem Ioseph a somno fecit, sicut praecepit ei angelus Domini, et accepit coniugem suam;"},
        {"verse":"25", "start":"218.2", "end": "224.7", "text":"et non cognoscebat eam, donec peperit filium, et vocavit nomen eius Iesum."}
      ]},
      {"chapter":"2", "audio":"matt02_extreme.mp3", "verses":[
        {"verse":"1", "start":"0  ", "end": "8.6", "text":"Cum autem natus esset Iesus in Bethlehem Iudaeae in diebus Herodis regis, ecce Magi ab oriente venerunt Hierosolymam"},
        {"verse":"2", "start":"8.82", "end": "19", "text":"dicentes: \"Ubi est, qui natus est, rex Iudaeorum? Vidimus enim stellam eius in oriente et venimus adorare eum\"."},
        {"verse":"3", "start":"20.3", "end": "25.5", "text":"Audiens autem Herodes rex turbatus est et omnis Hierosolyma cum illo;"},
        {"verse":"4", "start":"25.8", "end": "34", "text":"et congregans omnes principes sacerdotum et scribas populi, sciscitabatur ab eis ubi Christus nasceretur."},
        {"verse":"5", "start":"34.7", "end": "40.8", "text":"At illi dixerunt ei: “In Bethlehem Iudaeae. Sic enim scriptum est per prophetam:"},
        {"verse":"6", "start":"41", "end": "51.5", "text":"\"Et tu, Bethlehem terra Iudae, nequaquam minima es in principibus Iudae; ex te enim exiet dux, qui reget populum meum Israel\"."},
        {"verse":"7", "start":"52.5", "end": "60.5", "text":"Tunc Herodes, clam vocatis Magis, diligenter didicit ab eis tempus stellae, quae apparuit eis;"},
        {"verse":"8", "start":"60.9", "end": "74.3", "text":"et mittens illos in Bethlehem dixit: \"Ite et interrogate diligenter de puero; et cum inveneritis, renuntiate mihi, ut et ego veniens adorem eum\"."},
        {"verse":"9", "start":"75.3", "end": "87", "text":"Qui cum audissent regem, abierunt. Et ecce stella, quam viderant in oriente, antecedebat eos, usque dum veniens staret supra, ubi erat puer."},
        {"verse":"10", "start":"87", "end": "92", "text":"Videntes autem stellam gavisi sunt gaudio magno valde."},
        {"verse":"11", "start":"92.2", "end": "107.8", "text":"Et intrantes domum viderunt puerum cum Maria matre eius, et procidentes adoraverunt eum; et apertis thesauris suis, obtulerunt ei munera, aurum et tus et myrrham."},
        {"verse":"12", "start":"107", "end": "116.7", "text":"Et responso accepto in somnis, ne redirent ad Herodem, per aliam viam reversi sunt in regionem suam."},
        {"verse":"13", "start":"118", "end": "139", "text":"Qui cum recessissent, ecce angelus Domini apparet in somnis Ioseph dicens: \"Surge et accipe puerum et matrem eius et fuge in Aegyptum et esto ibi, usque dum dicam tibi; futurum est enim ut Herodes quaerat puerum ad perdendum eum\"."},
        {"verse":"14", "start":"139.6", "end": "146.8", "text":"Qui consurgens accepit puerum et matrem eius nocte et recessit in Aegyptum"},
        {"verse":"15", "start":"146.8", "end": "158.6", "text":"et erat ibi usque ad obitum Herodis, ut adimpleretur, quod dictum est a Domino per prophetam dicentem: \"Ex Aegypto vocavi filium meum\"."},
        {"verse":"16", "start":"158.7", "end": "178", "text":"Tunc Herodes videns quoniam illusus esset a Magis, iratus est valde et mittens occidit omnes pueros, qui erant in Bethlehem et in omnibus finibus eius, a bimatu et infra, secundum tempus, quod exquisierat a Magis."},
        {"verse":"17", "start":"178.8", "end": "183.7", "text":"Tunc adimpletum est, quod dictum est per Ieremiam prophetam dicentem:"},
        {"verse":"18", "start":"184", "end": "196", "text":"\"Vox in Rama audita est, ploratus et ululat us multus: Rachel plorans filios suos, et noluit consolari, quia non sunt\"."},
        {"verse":"19", "start":"197.2", "end": "202.8", "text":"Defuncto autem Herode, ecce apparet angelus Domini in somnis Ioseph in Aegypto"},
        {"verse":"20", "start":"203.8", "end": "213.4", "text":"dicens: \"Surge et accipe puerum et matrem eius et vade in terram Israel; defuncti sunt enim, qui quaerebant animam pueri\"."},
        {"verse":"21", "start":"214.3", "end": "220.2", "text":"Qui surgens accepit puerum et matrem eius et venit in terram Israel."},
        {"verse":"22", "start":"220.5", "end": "233", "text":"Audiens autem quia Archelaus regnaret in Iudaea pro Herode patre suo, timuit illuc ire; et admonitus in somnis, secessit in partes Galilaeae"},
        {"verse":"23", "start":"233", "end": "242.7", "text":"et veniens habitavit in civitate, quae vocatur Nazareth, ut adimpleretur, quod dictum est per Prophetas: \"Nazaraeus vocabitur\"."}
      ]}
      ]
    }
  ];
