var books = [{"book":"EVANGELIUM SECUNDUM MATTHAEUM", "chapters" : [{"chapter":"1", "audio":"matt01.ogg", "verses":[
        {"verse":"1", "start":"6", "end": "11.4", "text":"Liber generationis Iesu Christi filii David filii Abraham."},
        {"verse":"2", "start":"12", "end": "19.8", "text":"Abraham genuit Isaac, Isaac autem genuit Iacob, Iacob autem genuit Iudam et fratres eius,"},
        {"verse":"3", "start":"20", "end": "28.7", "text":"Iudas autem genuit Phares et Zara de Thamar, Phares autem genuit Esrom, Esrom autem genuit Aram,"},
        {"verse":"4", "start":"29", "end": "37", "text":"Aram autem genuit Aminadab, Aminadab autem genuit Naasson, Naasson autem genuit Salmon,"},
        {"verse":"5", "start":"37.2", "end": "46", "text":"Salmon autem genuit Booz de Rahab, Booz autem genuit Obed ex Ruth, Obed autem genuit Iesse,"},
        {"verse":"6", "start":"46", "end": "54", "text":"Iesse autem genuit David regem. David autem genuit Salomonem ex ea, quae fuit Uriae,"},
        {"verse":"7", "start":"54.1", "end": "61", "text":"Salomon autem genuit Roboam, Roboam autem genuit Abiam, Abia autem genuit Asa,"},
        {"verse":"8", "start":"61", "end": "67.5", "text":"Asa autem genuit Iosaphat, Iosaphat autem genuit Ioram, Ioram autem genuit Oziam,"},
        {"verse":"9", "start":"67.5", "end": "74", "text":"Ozias autem genuit Ioatham, Ioatham autem genuit Achaz, Achaz autem genuit Ezechiam,"},
        {"verse":"10", "start":"74", "end": "80.5", "text":"Ezechias autem genuit Manassen, Manasses autem genuit Amon, Amon autem genuit Iosiam,"},
        {"verse":"11", "start":"80.5", "end": "86", "text":"Iosias autem genuit Iechoniam et fratres eius in transmigratione Babylonis."},
        {"verse":"12", "start":"87", "end": "93", "text":"Et post transmigrationem Babylonis Iechonias genuit Salathiel, Salathiel autem genuit Zorobabel,"},
        {"verse":"13", "start":"93", "end": "99.7", "text":"Zorobabel autem genuit Abiud, Abiud autem genuit Eliachim, Eliachim autem genuit Azor,"},
        {"verse":"14", "start":"100", "end": "106.5", "text":"Azor autem genuit Sadoc, Sadoc autem genuit Achim, Achim autem genuit Eliud,"},
        {"verse":"15", "start":"106.5", "end": "113.2", "text":"Eliud autem genuit Eleazar, Eleazar autem genuit Matthan, Matthan autem genuit Iacob,"},
        {"verse":"16", "start":"114", "end": "121.2", "text":"Iacob autem genuit Ioseph virum Mariae, de qua natus est Iesus, qui vocatur Christus."},
        {"verse":"17", "start":"121.8", "end": "140.4", "text":"Omnes ergo generationes ab Abraham usque ad David generationes quattuordecim; et a David usque ad transmigrationem Babylonis generationes quattuordecim; et a transmigratione Babylonis usque ad Christum generationes quattuordecim."},
        {"verse":"18", "start":"141.6", "end": "154", "text":"Iesu Christi autem generatio sic erat. Cum esset desponsata mater eius Maria Ioseph, antequam convenirent inventa est in utero habens de Spiritu Sancto."},
        {"verse":"19", "start":"154.3", "end": "163.3", "text":"Ioseph autem vir eius, cum esset iustus et nollet eam traducere, voluit occulte dimittere eam."},
        {"verse":"20", "start":"164", "end": "180.5", "text":"Haec autem eo cogitante, ecce angelus Domini in somnis apparuit ei dicens: \"Ioseph fili David, noli timere accipere Mariam coniugem tuam. Quod enim in ea natum est, de Spiritu Sancto est;"},
        {"verse":"21", "start":"181", "end": "190", "text":"pariet autem filium, et vocabis nomen eius Iesum: ipse enim salvum faciet populum suum a peccatis eorum\"."},
        {"verse":"22", "start":"191.3", "end": "198.2", "text":"Hoc autem totum factum est, ut adimpleretur id, quod dictum est a Domino per prophetam dicentem:"},
        {"verse":"23", "start":"198.5", "end": "208.2", "text":"\"Ecce, virgo in utero habebit et pariet filium, et vocabunt nomen eius Emmanuel\", quod est interpretatum Nobiscum Deus."},
        {"verse":"24", "start":"209.5", "end": "218", "text":"Exsurgens autem Ioseph a somno fecit, sicut praecepit ei angelus Domini, et accepit coniugem suam;"},
        {"verse":"25", "start":"218.2", "end": "224.7", "text":"et non cognoscebat eam, donec peperit filium, et vocavit nomen eius Iesum."}
      ]},
      {"chapter":"2", "audio":"matt02_extreme.mp3", "verses":[
        {"verse":"1", "start":"0  ", "end": "8.6", "text":"Cum autem natus esset Iesus in Bethlehem Iudaeae in diebus Herodis regis, ecce Magi ab oriente venerunt Hierosolymam"},
        {"verse":"2", "start":"8.82", "end": "19", "text":"dicentes: \"Ubi est, qui natus est, rex Iudaeorum? Vidimus enim stellam eius in oriente et venimus adorare eum\"."},
        {"verse":"3", "start":"20.3", "end": "25.5", "text":"Audiens autem Herodes rex turbatus est et omnis Hierosolyma cum illo;"},
        {"verse":"4", "start":"25.8", "end": "34", "text":"et congregans omnes principes sacerdotum et scribas populi, sciscitabatur ab eis ubi Christus nasceretur."},
        {"verse":"5", "start":"34.7", "end": "40.8", "text":"At illi dixerunt ei: “In Bethlehem Iudaeae. Sic enim scriptum est per prophetam:"},
        {"verse":"6", "start":"41", "end": "51.5", "text":"\"Et tu, Bethlehem terra Iudae, nequaquam minima es in principibus Iudae; ex te enim exiet dux, qui reget populum meum Israel\"."},
        {"verse":"7", "start":"52.5", "end": "60.5", "text":"Tunc Herodes, clam vocatis Magis, diligenter didicit ab eis tempus stellae, quae apparuit eis;"},
        {"verse":"8", "start":"60.9", "end": "74.3", "text":"et mittens illos in Bethlehem dixit: \"Ite et interrogate diligenter de puero; et cum inveneritis, renuntiate mihi, ut et ego veniens adorem eum\"."},
        {"verse":"9", "start":"75.3", "end": "87", "text":"Qui cum audissent regem, abierunt. Et ecce stella, quam viderant in oriente, antecedebat eos, usque dum veniens staret supra, ubi erat puer."},
        {"verse":"10", "start":"87", "end": "92", "text":"Videntes autem stellam gavisi sunt gaudio magno valde."},
        {"verse":"11", "start":"92.2", "end": "107.8", "text":"Et intrantes domum viderunt puerum cum Maria matre eius, et procidentes adoraverunt eum; et apertis thesauris suis, obtulerunt ei munera, aurum et tus et myrrham."},
        {"verse":"12", "start":"107", "end": "116.7", "text":"Et responso accepto in somnis, ne redirent ad Herodem, per aliam viam reversi sunt in regionem suam."},
        {"verse":"13", "start":"118", "end": "139", "text":"Qui cum recessissent, ecce angelus Domini apparet in somnis Ioseph dicens: \"Surge et accipe puerum et matrem eius et fuge in Aegyptum et esto ibi, usque dum dicam tibi; futurum est enim ut Herodes quaerat puerum ad perdendum eum\"."},
        {"verse":"14", "start":"139.6", "end": "146.8", "text":"Qui consurgens accepit puerum et matrem eius nocte et recessit in Aegyptum"},
        {"verse":"15", "start":"146.8", "end": "158.6", "text":"et erat ibi usque ad obitum Herodis, ut adimpleretur, quod dictum est a Domino per prophetam dicentem: \"Ex Aegypto vocavi filium meum\"."},
        {"verse":"16", "start":"158.7", "end": "178", "text":"Tunc Herodes videns quoniam illusus esset a Magis, iratus est valde et mittens occidit omnes pueros, qui erant in Bethlehem et in omnibus finibus eius, a bimatu et infra, secundum tempus, quod exquisierat a Magis."},
        {"verse":"17", "start":"178.8", "end": "183.7", "text":"Tunc adimpletum est, quod dictum est per Ieremiam prophetam dicentem:"},
        {"verse":"18", "start":"184", "end": "196", "text":"\"Vox in Rama audita est, ploratus et ululat us multus: Rachel plorans filios suos, et noluit consolari, quia non sunt\"."},
        {"verse":"19", "start":"197.2", "end": "202.8", "text":"Defuncto autem Herode, ecce apparet angelus Domini in somnis Ioseph in Aegypto"},
        {"verse":"20", "start":"203.8", "end": "213.4", "text":"dicens: \"Surge et accipe puerum et matrem eius et vade in terram Israel; defuncti sunt enim, qui quaerebant animam pueri\"."},
        {"verse":"21", "start":"214.3", "end": "220.2", "text":"Qui surgens accepit puerum et matrem eius et venit in terram Israel."},
        {"verse":"22", "start":"220.5", "end": "233", "text":"Audiens autem quia Archelaus regnaret in Iudaea pro Herode patre suo, timuit illuc ire; et admonitus in somnis, secessit in partes Galilaeae"},
        {"verse":"23", "start":"233", "end": "242.7", "text":"et veniens habitavit in civitate, quae vocatur Nazareth, ut adimpleretur, quod dictum est per Prophetas: \"Nazaraeus vocabitur\"."}
      ]},
      {"chapter":"3", "audio":"matt03_extreme.mp3", "verses":[
        {"verse":"1", "start":"0", "end": "6", "text":"In diebus autem illis venit Ioannes Baptista praedicans in deserto Iudaeae"},
        {"verse":"2", "start":"6", "end": "11.1", "text":"et dicens: \"Paenitentiam agite; appropinquavit enim regnum caelorum\"."},
        {"verse":"3", "start":"11.5", "end": "21", "text":"Hic est enim, qui dictus est per Isaiam prophetam dicentem: \"Vox clamantis in deserto: \"Parate viam Domini, rectas facite semitas eius!\"\"."},
        {"verse":"4", "start":"22", "end": "34", "text":"Ipse autem Ioannes habebat vestimentum de pilis cameli et zonam pelliceam circa lumbos suos; esca autem eius erat locustae et mel silvestre."},
        {"verse":"5", "start":"34.5", "end": "40.9", "text":"Tunc exibat ad eum Hierosolyma et omnis Iudaea et omnis regio circa Iordanem,"},
        {"verse":"6", "start":"40.9", "end": "46.3", "text":"et baptizabantur in Iordane flumine ab eo, confitentes peccata sua."},
        {"verse":"7", "start":"47", "end": "60.3", "text":"Videns autem multos pharisaeorum et sadducaeorum venientes ad baptismum suum, dixit eis: \"Progenies viperarum, quis demonstravit vobis fugere a futura ira?"},
        {"verse":"8", "start":"60.4", "end": "64", "text":"Facite ergo fructum dignum paenitentiae"},
        {"verse":"9", "start":"63.7", "end": "76.2", "text":"et ne velitis dicere intra vos: \"Patrem habemus Abraham\"; dico enim vobis quoniam potest Deus de lapidibus istis suscitare Abrahae filios."},
        {"verse":"10", "start":"76", "end": "88", "text":"Iam enim securis ad radicem arborum posita est; omnis ergo arbor, quae non facit fructum bonum, exciditur et in ignem mittitur."},
        {"verse":"11", "start":"87.8", "end": "104", "text":"Ego quidem vos baptizo in aqua in paenitentiam; qui autem post me venturus est, fortior me est, cuius non sum dignus calceamenta portare; ipse vos baptizabit in Spiritu Sancto et igni,"},
        {"verse":"12", "start":"103.8", "end": "116.2", "text":"cuius ventilabrum in manu sua, et permundabit aream suam et congregabit triticum suum in horreum, paleas autem comburet igni inexstinguibili\"."},
        {"verse":"13", "start":"118.5", "end": "125.2", "text":"Tunc venit Iesus a Galilaea in Iordanem ad Ioannem, ut baptizaretur ab eo."},
        {"verse":"14", "start":"124.7", "end": "132.7", "text":"Ioannes autem prohibebat eum dicens: \"Ego a te debeo baptizari, et tu venis ad me?\"."},
        {"verse":"15", "start":"132.8", "end": "144", "text":"Respondens autem Iesus dixit ei: “Sine modo, sic enim decet nos implere omnem iustitiam”. Tunc dimittit eum."},
        {"verse":"16", "start":"144", "end": "157.5", "text":"Baptizatus autem Iesus, confestim ascendit de aqua; et ecce aperti sunt ei caeli, et vidit Spiritum Dei descendentem sicut columbam et venientem super se."},
        {"verse":"17", "start":"157.5", "end": "164.7", "text":"Et ecce vox de caelis dicens: \"Hic est Filius meus dilectus, in quo mihi complacui\"."}
      ]},
      {"chapter":"4", "audio":"matt04_extreme.mp3", "verses":[
        {"verse":"1", "start":"0", "end": "5.6", "text":"Tunc Iesus ductus est in desertum a Spiritu, ut tentaretur a Diabolo."},
        {"verse":"2", "start":"5.7", "end": "12", "text":"Et cum ieiunasset quadraginta diebus et quadraginta noctibus, postea esuriit."},
        {"verse":"3", "start":"12.3", "end": "20.82", "text":"Et accedens tentator dixit ei: \"Si Filius Dei es, dic, ut lapides isti panes fiant\"."},
        {"verse":"4", "start":"21.1", "end": "31", "text":"Qui respondens dixit: \"Scriptum est: \"Non in pane solo vivet homo, sed in omni verbo, quod procedit de ore Dei\"\"."},
        {"verse":"5", "start":"32", "end": "39", "text":"Tunc assumit eum Diabolus in sanctam civitatem et statuit eum supra pinnaculum templi"},
        {"verse":"6", "start":"39.2", "end": "54", "text":"et dicit ei: \"Si Filius Dei es, mitte te deorsum. Scriptum est enim: \"Angelis suis mandabit de te, et in manibus tollent te, ne forte offendas ad lapidem pedem tuum\"\"."},
        {"verse":"7", "start":"54.5", "end": "61.3", "text":"Ait illi Iesus: \"Rursum scriptum est: \"Non tentabis Dominum Deum tuum\"\"."},
        {"verse":"8", "start":"62.6", "end": "70.7", "text":"Iterum assumit eum Diabolus in montem excelsum valde et ostendit ei omnia regna mundi et gloriam eorum"},
        {"verse":"9", "start":"71.5", "end": "78.1", "text":"et dicit illi: \"Haec tibi omnia dabo, si cadens adoraveris me\"."},
        {"verse":"10", "start":"78.4", "end": "90", "text":"Tunc dicit ei Iesus: \"Vade, Satanas! Scriptum est enim: \"Dominum Deum tuum adorabis et illi soli servies\"\"."},
        {"verse":"11", "start":"90.2", "end": "97.3", "text":"Tunc reliquit eum Diabolus, et ecce angeli accesserunt et ministrabant ei."},
        {"verse":"12", "start":"98.6", "end": "104.2", "text":"Cum autem audisset quod Ioannes traditus esset, secessit in Galilaeam."},
        {"verse":"13", "start":"104.8", "end": "109.7", "text":"Et relicta Nazareth, venit et habitavit in Capharnaum maritimam"},
        {"verse":"14", "start":"110", "end": "116.8", "text":"in finibus Zabulon et Nephthali, ut impleretur, quod dictum est per Isaiam prophetam dicentem:"},
        {"verse":"15", "start":"116.8", "end": "123.5", "text":"\"Terra Zabulon et terra Nephthali, ad viam maris, trans Iordanem, Galilaea gentium;"},
        {"verse":"16", "start":"123.7", "end": "133", "text":"populus, qui sedebat in tenebris, lucem vidit magnam, et sedentibus in regione et umbra mortis lux orta est eis\"."},
        {"verse":"17", "start":"134", "end": "142.4", "text":"Exinde coepit Iesus praedicare et dicere: \"Paenitentiam agite; appropinquavit enim regnum caelorum\"."},
        {"verse":"18", "start":"144.2", "end": "157.3", "text":"Ambulans autem iuxta mare Galilaeae, vidit duos fratres, Simonem, qui vocatur Petrus, et Andream fratrem eius, mittentes rete in mare; erant enim piscatores."},
        {"verse":"19", "start":"157.5", "end": "163.5", "text":"Et ait illis: \"Venite post me, et faciam vos piscatores hominum\"."},
        {"verse":"20", "start":"163.5", "end": "169.3", "text":"At illi continuo, relictis retibus, secuti sunt eum."},
        {"verse":"21", "start":"169.5", "end": "183.8", "text":"Et procedens inde vidit alios duos fratres, Iacobum Zebedaei et Ioannem fratrem eius, in navi cum Zebedaeo patre eorum reficientes retia sua; et vocavit eos."},
        {"verse":"22", "start":"183.8", "end": "189.9", "text":"Illi autem statim, relicta navi et patre suo, secuti sunt eum."},
        {"verse":"23", "start":"191", "end": "203.5", "text":"Et circumibat Iesus totam Galilaeam, docens in synagogis eorum et praedicans evangelium regni et sanans omnem languorem et omnem infirmitatem in populo."},
        {"verse":"24", "start":"203.9", "end": "219.7", "text":"Et abiit opinio eius in totam Syriam; et obtulerunt ei omnes male habentes, variis languoribus et tormentis comprehensos, et qui daemonia habebant, et lunaticos et paralyticos, et curavit eos."},
        {"verse":"25", "start":"219.7", "end": "228.5", "text":"Et secutae sunt eum turbae multae de Galilaea et Decapoli et Hierosolymis et Iudaea et de trans Iordanem."}
      ]},
      {"chapter":"5", "audio":"matt05_extreme.mp3", "verses":[
        {"verse":"1", "start":"0", "end": "7.9", "text":"Videns autem turbas, ascendit in montem; et cum sedisset, ac cesserunt ad eum discipuli eius;"},
        {"verse":"2", "start":"7.1", "end": "12.7", "text":"et aperiens os suum docebat eos dicens:"},
        {"verse":"3", "start":"12.9", "end": "19.2", "text":"\"Beati pauperes spiritu, quoniam ipsorum est regnum caelorum."},
        {"verse":"4", "start":"19.2", "end": "23.6", "text":"Beati, qui lugent, quoniam ipsi consolabuntur."},
        {"verse":"5", "start":"23.2", "end": "27.4", "text":"Beati mites, quoniam ipsi possidebunt terram."},
        {"verse":"6", "start":"27.2", "end": "33.6", "text":"Beati, qui esuriunt et sitiunt iustitiam, quoniam ipsi saturabuntur."},
        {"verse":"7", "start":"33.3", "end": "38.6", "text":"Beati misericordes, quia ipsi misericordiam consequentur."},
        {"verse":"8", "start":"38.8", "end": "43.9", "text":"Beati mundo corde, quoniam ipsi Deum videbunt."},
        {"verse":"9", "start":"43.9", "end": "48", "text":"Beati pacifici, quoniam filii Dei vocabuntur."},
        {"verse":"10", "start":"48.2", "end": "55.9", "text":"Beati, qui persecutionem patiuntur propter iustitiam, quoniam ipsorum est regnum caelorum."},
        {"verse":"11", "start":"55.7", "end": "66.3", "text":"Beati estis cum maledixerint vobis et persecuti vos fuerint et dixerint omne malum adversum vos, mentientes, propter me."},
        {"verse":"12", "start":"65.9", "end": "76.2", "text":"Gaudete et exsultate, quoniam merces vestra copiosa est in caelis; sic enim persecuti sunt prophetas, qui fuerunt ante vos."},
        {"verse":"13", "start":"76.4", "end": "89", "text":"Vos estis sal terrae; quod si sal evanuerit, in quo salietur? Ad nihilum valet ultra, nisi ut mittatur foras et conculcetur ab hominibus."},
        {"verse":"14", "start":"89", "end": "96.4", "text":"Vos estis lux mundi. Non potest civitas abscondi supra montem posita;"},
        {"verse":"15", "start":"96.5", "end": "104.7", "text":"neque accendunt lucernam et ponunt eam sub modio, sed super candelabrum, ut luceat omnibus, qui in domo sunt."},
        {"verse":"16", "start":"104.7", "end": "114.2", "text":"Sic luceat lux vestra coram hominibus, ut videant vestra bona opera et glorificent Patrem vestrum, qui in caelis est."},
        {"verse":"17", "start":"115", "end": "122.3", "text":"Nolite putare quoniam veni solvere Legem aut Prophetas; non veni solvere, sed adimplere."},
        {"verse":"18", "start":"121.2", "end": "133.8", "text":"Amen quippe dico vobis: Donec transeat caelum et terra, iota unum aut unus apex non praeteribit a Lege, donec omnia fiant."},
        {"verse":"19", "start":"133.2", "end": "148.9", "text":"Qui ergo solverit unum de mandatis istis minimis et docuerit sic homines, minimus vocabitur in regno caelorum; qui autem fecerit et docuerit, hic magnus vocabitur in regno caelorum."},
        {"verse":"20", "start":"148.9", "end": "159.5", "text":"Dico enim vobis: Nisi abundaverit iustitia vestra plus quam scribarum et pharisaeorum, non intrabitis in regnum caelorum."},
        {"verse":"21", "start":"159.5", "end": "167.8", "text":"Audistis quia dictum est antiquis: \"Non occides; qui autem occiderit, reus erit iudicio\"."},
        {"verse":"22", "start":"167.2", "end": "185", "text":"Ego autem dico vobis: Omnis, qui irascitur fratri suo, reus erit iudicio; qui autem dixerit fratri suo: \"Racha\", reus erit concilio; qui autem dixerit: \"Fatue\", reus erit gehennae ignis."},
        {"verse":"23", "start":"185.3", "end": "196.3", "text":"Si ergo offeres munus tuum ad altare, et ibi recordatus fueris quia frater tuus habet aliquid adversum te,"},
        {"verse":"24", "start":"196.3", "end": "208.1", "text":"relinque ibi munus tuum ante altare et vade, prius, reconciliare fratri tuo et tunc veniens offer munus tuum."},
        {"verse":"25", "start":"208.1", "end": "222.8", "text":"Esto consentiens adversario tuo cito, dum es in via cum eo, ne forte tradat te adversarius iudici, et iudex tradat te ministro, et in carcerem mittaris."},
        {"verse":"26", "start":"222.8", "end": "229.7", "text":"Amen dico tibi: Non exies inde, donec reddas novissimum quadrantem."},
        {"verse":"27", "start":"230", "end": "236", "text":"Audistis quia dictum est: \"Non moechaberis\"."},
        {"verse":"28", "start":"234", "end": "245.6", "text":"Ego autem dico vobis: Omnis, qui viderit mulierem ad concupiscendum eam, iam moechatus est eam in corde suo."},
        {"verse":"29", "start":"244", "end": "262", "text":"Quod si oculus tuus dexter scandalizat te, erue eum et proice abs te; expedit enim tibi, ut pereat unum membrorum tuorum, quam totum corpus tuum mittatur in gehennam."},
        {"verse":"30", "start":"260.4", "end": "277", "text":"Et si dextera manus tua scandalizat te, abscide eam et proice abs te; expedit enim tibi, ut pereat unum membrorum tuorum, quam totum corpus tuum abeat in gehennam."},
        {"verse":"31", "start":"275", "end": "285", "text":"Dictum est autem: \"Quicumque dimiserit uxorem suam, det illi libellum repudii\"."},
        {"verse":"32", "start":"283.5", "end": "298.5", "text":"Ego autem dico vobis: Omnis, qui dimiserit uxorem suam, excepta fornicationis causa, facit eam moechari; et, qui dimissam duxerit, adulterat."},
        {"verse":"33", "start":"297.5", "end": "306.3", "text":"Iterum audistis quia dictum est antiquis: \"Non periurabis; reddes autem Domino iuramenta tua\"."},
        {"verse":"34", "start":"305", "end": "313.5", "text":"Ego autem dico vobis: Non iurare omnino, neque per caelum, quia thronus Dei est,"},
        {"verse":"35", "start":"312", "end": "320.8", "text":"neque per terram, quia scabellum est pedum eius, neque per Hierosolymam, quia civitas est magni Regis;"},
        {"verse":"36", "start":"319.2", "end": "327", "text":"neque per caput tuum iuraveris, quia non potes unum capillum album facere aut nigrum."},
        {"verse":"37", "start":"326", "end": "336.5", "text":"Sit autem sermo vester: \"Est, est\", \"Non, non\"; quod autem his abundantius est, a Malo est."},
        {"verse":"38", "start":"337", "end": "344.4", "text":"Audistis quia dictum est: \"Oculum pro oculo et dentem pro dente\"."},
        {"verse":"39", "start":"344", "end": "355", "text":"Ego autem dico vobis: Non resistere malo; sed si quis te percusserit in dextera maxilla tua, praebe illi et alteram;"},
        {"verse":"40", "start":"354.4", "end": "362.4", "text":"et ei, qui vult tecum iudicio contendere et tunicam tuam tollere, remitte ei et pallium;"},
        {"verse":"41", "start":"362", "end": "369", "text":"et quicumque te angariaverit mille passus, vade cum illo duo."},
        {"verse":"42", "start":"368", "end": "375", "text":"Qui petit a te, da ei; et volenti mutuari a te, ne avertaris."},
        {"verse":"43", "start":"375.8", "end": "383.7", "text":"Audistis quia dictum est: \"Diliges proximum tuum et odio habebis inimicum tuum\"."},
        {"verse":"44", "start":"382.8", "end": "390.9", "text":"Ego autem dico vobis: Diligite inimicos vestros et orate pro persequentibus vos,"},
        {"verse":"45", "start":"390", "end": "402", "text":"ut sitis filii Patris vestri, qui in caelis est, quia solem suum oriri facit super malos et bonos et pluit super iustos et iniustos."},
        {"verse":"46", "start":"401", "end": "410", "text":"Si enim dilexeritis eos, qui vos diligunt, quam mercedem habetis? Nonne et publicani hoc faciunt?"},
        {"verse":"47", "start":"409.2", "end": "418", "text":"Et si salutaveritis fratres vestros tantum, quid amplius facitis? Nonne et ethnici hoc faciunt?"},
        {"verse":"48", "start":"417.7", "end": "424", "text":"Estote ergo vos perfecti, sicut Pater vester caelestis perfectus est."}
      ]},
      {"chapter":"6", "audio":"matt06_extreme.mp3", "verses":[
        {"verse":"1", "start":"0  ", "end": "11", "text":"Attendite, ne iustitiam vestram faciatis coram hominibus, ut vi deamini ab eis; alioquin mercedem non habetis apud Patrem vestrum, qui in caelis est."},
        {"verse":"2", "start":"11", "end": "26.6", "text":"Cum ergo facies eleemosynam, noli tuba canere ante te, sicut hypocritae faciunt in synagogis et in vicis, ut honorificentur ab hominibus. Amen dico vobis: Receperunt mercedem suam."},
        {"verse":"3", "start":"26.8", "end": "33.5", "text":"Te autem faciente eleemosynam, nesciat sinistra tua quid faciat dextera tua,"},
        {"verse":"4", "start":"33.3", "end": "41.8", "text":"ut sit eleemosyna tua in abscondito, et Pater tuus, qui videt in abscondito, reddet tibi."},
        {"verse":"5", "start":"42.2", "end": "56", "text":"Et cum oratis, non eritis sicut hypocritae, qui amant in synagogis et in angulis platearum stantes orare, ut videantur ab hominibus. Amen dico vobis: Receperunt mercedem suam."},
        {"verse":"6", "start":"56", "end": "71.6", "text":"Tu autem cum orabis, intra in cubiculum tuum et, clauso ostio tuo, ora Patrem tuum, qui est in abscondito; et Pater tuus, qui videt in abscondito, reddet tibi."},
        {"verse":"7", "start":"72", "end": "80", "text":"Orantes autem nolite multum loqui sicut ethnici; putant enim quia in multiloquio suo exaudiantur."},
        {"verse":"8", "start":"80.2", "end": "90", "text":"Nolite ergo assimilari eis; scit enim Pater vester, quibus opus sit vobis, antequam petatis eum."},
        {"verse":"9", "start":"90", "end": "98.4", "text":"Sic ergo vos orabitis: Pater noster, qui es in caelis, sanctificetur nomen tuum,"},
        {"verse":"10", "start":"98.4", "end": "104.5", "text":"adveniat regnum tuum, fiat voluntas tua, sicut in caelo, et in terra."},
        {"verse":"11", "start":"104.5", "end": "109", "text":"Panem nostrum supersubstantialem da nobis hodie;"},
        {"verse":"12", "start":"108.8", "end": "114.3", "text":"et dimitte nobis debita nostra, sicut et nos dimittimus debitoribus nostris;"},
        {"verse":"13", "start":"114.3", "end": "120", "text":"et ne inducas nos in tentationem, sed libera nos a Malo."},
        {"verse":"14", "start":"120.3", "end": "128.2", "text":"Si enim dimiseritis hominibus peccata eorum, dimittet et vobis Pater vester caelestis;"},
        {"verse":"15", "start":"128.2", "end": "134.6", "text":"si autem non dimiseritis hominibus, nec Pater vester dimittet peccata vestra."},
        {"verse":"16", "start":"134.6", "end": "148.3", "text":"Cum autem ieiunatis, nolite fieri sicut hypocritae tristes; demoliuntur enim facies suas, ut pareant hominibus ieiunantes. Amen dico vobis: Receperunt mercedem suam."},
        {"verse":"17", "start":"148.3", "end": "154", "text":"Tu autem cum ieiunas, unge caput tuum et faciem tuam lava,"},
        {"verse":"18", "start":"154", "end": "164.8", "text":"ne videaris hominibus ieiunans sed Patri tuo, qui est in abscondito; et Pater tuus, qui videt in abscondito, reddet tibi."},
        {"verse":"19", "start":"166", "end": "175.4", "text":"Nolite thesaurizare vobis thesauros in terra, ubi aerugo et tinea demolitur, et ubi fures effodiunt et furantur;"},
        {"verse":"20", "start":"177", "end": "187.2", "text":"thesaurizate autem vobis thesauros in caelo, ubi neque aerugo neque tinea demolitur, et ubi fures non effodiunt nec furantur;"},
        {"verse":"21", "start":"187.2", "end": "192.4", "text":"ubi enim est thesaurus tuus, ibi erit et cor tuum."},
        {"verse":"22", "start":"193.7", "end": "203.3", "text":"Lucerna corporis est oculus. Si ergo fuerit oculus tuus simplex, totum corpus tuum lucidum erit;"},
        {"verse":"23", "start":"204.3", "end": "219.5", "text":"si autem oculus tuus nequam fuerit, totum corpus tuum tenebrosum erit. Si ergo lumen, quod in te est, tenebrae sunt, tenebrae quantae erunt!"},
        {"verse":"24", "start":"222", "end": "237.3", "text":"Nemo potest duobus dominis servire: aut enim unum odio habebit et alterum diliget, aut unum sustinebit et alterum contemnet; non potestis Deo servire et mammonae."},
        {"verse":"25", "start":"236", "end": "252.5", "text":"Ideo dico vobis: Ne solliciti sitis animae vestrae quid manducetis, neque corpori vestro quid induamini. Nonne anima plus est quam esca, et corpus quam vestimentum?"},
        {"verse":"26", "start":"251.4", "end": "267.3", "text":"Respicite volatilia caeli, quoniam non serunt neque metunt neque congregant in horrea, et Pater vester caelestis pascit illa. Nonne vos magis pluris estis illis?"},
        {"verse":"27", "start":"267.3", "end": "273.4", "text":"Quis autem vestrum cogitans potest adicere ad aetatem suam cubitum unum?"},
        {"verse":"28", "start":"273.5", "end": "281.5", "text":"Et de vestimento quid solliciti estis? Considerate lilia agri quomodo crescunt: non laborant neque nent."},
        {"verse":"29", "start":"281.8", "end": "289.4", "text":"Dico autem vobis quoniam nec Salomon in omni gloria sua coopertus est sicut unum ex istis."},
        {"verse":"30", "start":"289", "end": "300.4", "text":"Si autem fenum agri, quod hodie est et cras in clibanum mittitur, Deus sic vestit, quanto magis vos, modicae fidei?"},
        {"verse":"31", "start":"300.4", "end": "307.8", "text":"Nolite ergo solliciti esse dicentes: \"Quid manducabimus?\", aut: \"Quid bibemus?\", aut: \"Quo operiemur?\"."},
        {"verse":"32", "start":"307.8", "end": "316.9", "text":"Haec enim omnia gentes inquirunt; scit enim Pater vester caelestis quia his omnibus indigetis."},
        {"verse":"33", "start":"316.6", "end": "324.3", "text":"Quaerite autem primum regnum Dei et iustitiam eius, et haec omnia adicientur vobis."},
        {"verse":"34", "start":"324.3", "end": "335", "text":"Nolite ergo esse solliciti in crastinum; crastinus enim dies sollicitus erit sibi ipse. Sufficit diei malitia sua."}
      ]}
      ]
    }
  ];
